#! /bin/bash

level=`awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master)`
channel=`awk -F"[][]" '/Left:/ { print $4 }' <(amixer sget Master)`
if [ $channel == "on" ]; then
	echo " $level"
else
	echo ""
fi
