#! /bin/bash

if [ -z "$1" ]; then
    echo "You must provide an url";
    exit;
fi

youtube-dl --rm-cache-dir
youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' $1 --extract-audio --audio-format mp3 --playlist-start $2
